Profiles:
  delphiGenesis:
    Capabilities:
      V1_3: true
    Orderer:
      BatchTimeout: 1s
      BatchSize:
        MaxMessageCount: 1
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
      Capabilities:
        V1_1: true
      OrdererType: solo
      Addresses:
        - 'orderer.Delphi.com:7050'
      Organizations:
        - Name: Delphi.com
          ID: OrdererMSP
          MSPDir: /Users/stevencheung/delphi-fabric/config/ca-crypto-config/ordererOrganizations/Delphi.com/msp
    Consortiums:
      SampleConsortium:
        Organizations:
          - Name: ASTRI.org
            ID: ASTRIMSP
            MSPDir: /Users/stevencheung/delphi-fabric/config/ca-crypto-config/peerOrganizations/ASTRI.org/msp
          - Name: icdd
            ID: icdd
            MSPDir: /Users/stevencheung/delphi-fabric/config/ca-crypto-config/peerOrganizations/icdd/msp
  allchannel:
    Capabilities:
      V1_3: true
    Consortium: SampleConsortium
    Application:
      Organizations:
        - Name: ASTRI.org
          ID: ASTRIMSP
          MSPDir: /Users/stevencheung/delphi-fabric/config/ca-crypto-config/peerOrganizations/ASTRI.org/msp
          AnchorPeers:
            - {}
        - Name: icdd
          ID: icdd
          MSPDir: /Users/stevencheung/delphi-fabric/config/ca-crypto-config/peerOrganizations/icdd/msp
          AnchorPeers:
            - {}
      Capabilities:
        V1_3: true
  anchorPeers:
    Application:
      Organizations:
        - Name: ASTRI.org
          AnchorPeers:
            - Host: peer0.ASTRI.org
              Port: 7051
        - Name: icdd
          AnchorPeers:
            - Host: peer0.icdd
              Port: 7051
